@url_dev=http://localhost:3056/v1/api

### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop TIPS",
    "email": "shoptipjs05gmail.com",
    "password": "abc123"
}